name: Deploy Terraform Resources

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GitHub_Token: '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'

permissions:
  actions: write
  issues: read
  contents: read
  pull-requests: read
  id-token: write

jobs:
  Terraform:
    name: "Terraform Init"
    runs-on: ubuntu-latest
  
    environment: production
    steps:
      - name: Checkout Self
        uses: actions/checkout@v6.0.2
        with:
          repository:  ${{ github.repository }}
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: latest
      - name: Terraform fmt
        id: fmt
        run: terraform fmt
      - name: Terraform Init
        id: init
        run: terraform init
        
  TerraformValidate:
     name: Terraform validate
     runs-on: ubuntu-latest
   
     environment: production
     steps:
       - name:  Checkout Self
         uses: actions/checkout@v6.0.2
         with:
           repository:  ${{ github.repository }}
       - name: Install Terraform
         uses: hashicorp/setup-terraform@v2.0.3
         with:
           terraform_version: latest
       - name: Terraform Init
         run: terraform init
       - name: Terraform Validate
         id: validate
         run: terraform validate -no-color
  TFLint:
    name: 'Terraform Lint'
    needs: 'TerraformValidate'
    runs-on: ${{ matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        name: Checkout source code
  
      - uses: actions/cache@v4
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}
  
      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          tflint_version: v0.52.0
      - name: Show version
        run: tflint --version
  
      - name: Init TFLint
        run: tflint --init
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ env.GitHub_Token }}
  
      - name: Run TFLint
        run: tflint -f compact
        
  CheckOv:
    name: CheckOV
    runs-on: ${{ matrix.os}}
    environment: production
    needs: TFLint
    permissions: 
      contents: read
      security-events: write
      actions: write
      id-token: write
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout Self
        uses: actions/checkout@v4
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          # This will add both a CLI output to the console and create a results.sarif file
          output_format: cli,sarif
          output_file_path: console,results.sarif
          soft_fail: true
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        
        # Results are generated only on a success or failure
        # this is required since GitHub by default won't run the next step
        # when the previous one has failed. Security checks that do not pass will 'fail'.
        # An alternative is to add `continue-on-error: true` to the previous step
        # Or 'soft_fail: true' to checkov.
        if: success() || failure()
        with:
          sarif_file: results.sarif
    
    
     
       
